# -----------------------------
# Prefix
# -----------------------------
set -g prefix C-b        # Default prefix Ctrl+b
unbind C-b
bind C-b send-prefix

# -----------------------------
# Indexing
# -----------------------------
set -g base-index 1             # Windows start at 1
setw -g pane-base-index 1       # Panes start at 1

# -----------------------------
# Mouse behavior
# -----------------------------
set -g mouse off                # Disable tmux mouse → terminal handles scrolling & copy

# -----------------------------
# Pane shortcuts
# -----------------------------
bind | split-window -h          # Split pane horizontally
bind - split-window -v          # Split pane vertically

# Reload config if edited
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
